### ISSUE TITLE
Replicate parts but not tracks

### ISSUE THREAD

**Issue by hildogjr** [MitjaNemec/Kicad_action_plugins#18]
Last try of replicate plugins, I got the replicated placement but not the tracks and vias. The error:

Traceback (most recent call last):
  File "/home/h/.kicad_plugins/replicate_layout/action_replicate_layout.py", line 302, in Run
    polar)
  File "/home/h/.kicad_plugins/replicate_layout/replicatelayout.py", line 943, in replicate_layout
    self.replicate_tracks(x_offset, y_offset, polar)
  File "/home/h/.kicad_plugins/replicate_layout/replicatelayout.py", line 764, in replicate_tracks
    net_pairs, net_dict = self.get_net_pairs(sheet)
  File "/home/h/.kicad_plugins/replicate_layout/replicatelayout.py", line 478, in get_net_pairs
    index = match_len.index(max(match_len))
ValueError: max() arg is an empty sequence

**Comment by hildogjr** [comment]
I did some debug and appear to be related with the machine (using some Nightly version). I will update the Nightly on it and check again.

**Comment by hildogjr** [comment]
This problem is not present anymore on recent code releases.
